require 'rails/generators'

module ActivePostgrest
  module Generators
    class ModelGenerator < Rails::Generators::Base
      argument :name, type: :string, desc: 'Table name, e.g. users'

      def generate_attributes_concern
        klass = singular.camelize
        defn  = ActivePostgrest::Base.connection.table_schema(table)
        props = defn['properties'] || {}

        attrs = props.filter_map do |col, info|
          type = ActivePostgrest::Base::POSTGRES_TYPE_CAST[info['format']]
          "    attribute :#{col}, :#{type}" if type
        end

        content = <<~RUBY
          # Auto-generated by `rails g active_postgrest:model #{name}`. Do not edit manually.
          module #{klass}Attributes
            extend ActiveSupport::Concern
            included do
          #{attrs.any? ? attrs.join("\n") : '    # no type casts needed'}
            end
          end
        RUBY

        create_file("app/models/concerns/#{singular}_attributes.rb", content, force: true)
      end

      def create_model_file
        path = "app/models/#{singular}.rb"

        if File.exist?(File.join(destination_root, path))
          say_status :exist, path, :blue
          say "        → add `include #{singular.camelize}Attributes` to #{path} if not present", :cyan
        else
          create_file(path, <<~RUBY)
            class #{singular.camelize} < ActivePostgrest::Base
              include #{singular.camelize}Attributes
            end
          RUBY
        end
      end

      private

      def table    = name.tableize
      def singular = table.singularize
    end
  end
end
