# Auto-generated by `rails g postgrest:model company`. Do not edit manually.
module CompanyAttributes
  extend ActiveSupport::Concern
  included do
    attribute :created_at, :datetime
    attribute :updated_at, :datetime
  end
end
