# Auto-generated by `rails g postgrest:model users`. Do not edit manually.
module UserAttributes
  extend ActiveSupport::Concern
  included do
    attribute :birth_date, :date
    attribute :created_at, :datetime
    attribute :updated_at, :datetime
  end
end
